/*
Author: tal
This snippet was generated by http://swift.menu a tool for building a helper library
and could be found at: http://swift.menu/snippet/_07cdb52274e9b19
*/

public enum TestFoo: Omg {
    case one, two, three
}