/*
Author: tal
This snippet was generated by http://swift.menu a tool for building a helper library
and can be found at: http://swift.menu/snippet/_dd79405e4668d5f
*/

public enum TestFoo {
    case one, two, three, four
}
